name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Servicing Dependencies Directly
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyserial pyusb pycryptodome

    - name: Compile Script to EXE via PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Upload Finished EXE Application
      uses: actions/upload-artifact@v4
      with:
        name: Nokia-Hardware-Reset-Tool
        path: dist/main.exe
